---
title: "transcript_abundances"
author: "Tanvi Ingle"
date: "8/20/2021"
output: html_document
---

## Objective

Here I create a function to plot transcript abundances from phix174 model outputs

### Get libraries
```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(cowplot)
```

### General function to plot normalized transcript abundances
```{r}

plot_abundances <- function(basedir, filename, timestamp){

my_palette = c("#d0a34f","#75c130", "#c12c04", "#ecd575", "#b69507",
            "#e37c71", "#adcb40", "#d3ad40", "#288ede", "#a5bdfa",
            "#93c9ff")
fig <- read_tsv(paste0(basedir, filename)) %>% 
       mutate(time = round(time)) %>% 
       filter(time == timestamp) %>% 
       filter(!str_detect(species, '__|bound|ecoli|promoter')) %>% 
       mutate(normalized = transcript/transcript[1]) %>% 
       mutate(species = factor(species, c("gene_A", "gene_A*", "gene_B",
                                         "gene_K", "gene_C", "gene_D",
                                         "gene_E", "gene_J", "gene_F",
                                         "gene_G", "gene_H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
       ggplot(aes(x=species, y=normalized, fill = species)) +
       geom_bar(stat="identity", color = "black") + 
       scale_fill_manual(values = my_palette) + 
       #scale_color_manual(values = "black") + 
       scale_y_continuous(limits = c(0, 18), 
                          breaks = c(0,3,6,9,12,15,18)) + 
       ylab("Transcript abundances normalized to gene A") + 
       #geom_hline(yintercept=1, linetype="dashed", color = "red") + 
       #geom_hline(yintercept=6, linetype="dashed", color = "red") + 
       #geom_hline(yintercept=17, linetype="dashed", color = "red") + 
       #geom_hline(yintercept=11, linetype="dashed", color = "red") + 
       #geom_hline(yintercept=5, linetype="dashed", color = "red") + 
       cowplot::theme_cowplot(12) +
       theme(legend.position = "none") 

return(fig)
}

```


### Set directories & Parameters
```{r}
basedir = "/Users/tanviingle/Documents/Wilke/phix174/output/opt_test/"
filename = "manual_20.tsv"
timestamp = 1200

#plot_abundances(basedir, "gen_0.tsv", timestamp)
plot_abundances(basedir, "manual_1.tsv", 1200)
plot_abundances(basedir, "manual_2.tsv", 1200)
#plot_abundances(basedir, "gen_0.tsv", 1400)
#plot_abundances(basedir, "gen_0.tsv", 2400)
#plot_abundances(basedir, "gen_1.tsv", timestamp)
#plot_abundances(basedir, "gen_1.tsv", 1200)
```


```{r}

#d0a34f = A
#75c130 = A*
#c12c04 = B
#ecd575 = K
#b69507 = C
#e37c71 = D
#adcb40 = E
#d3ad40 = J
#288ede = F
#a5bdfa = G
#93c9ff = H

```







