---
title: "Analysis"
author: "Alexis Hill"
date: "09/23/2023"
output: html_document
---

### Libraries
```{r, echo = FALSE, message = FALSE, warning=FALSE}
require(ggplot2)
require(tidyverse)
require(cowplot)
require(scales)
require(kableExtra)
require(RColorBrewer)
```

#### Summary
Fit Logel proposed model (new prom & terminator in second gene grouping) to high-resolution RNA-seq data

Common Functions & Base directory 
```{r, echo = FALSE, message = FALSE, warning=FALSE}
# Functions & Variables I use a lot
date <- "09232023"
filedir <- paste("../../../../output/", date, "/", sep="")

my_palette = c('#8C4C47', '#C27F7A', '#21819F', '#65AFCF', '#93D8F8', '#398048', '#73B47E', '#97D8A2', '#A56EA9', '#C994CE', '#EDB7F2')

# get_reports() retrieves the reports for all the simulation runs in a specified scenario
# had hardcoded case for Scenario B where there is no simulation 1
get_reports <- function(filedir){
  report <- data.frame()
   batch <- 1:20

  
  for(i in batch){
     sim = read_csv(paste0(filedir, "", "sim_", i, "_report.csv")) 
     sim$sim = i
     report <- rbind(report, sim)}
  return(report)
}

get_single_report <- function(filedir, sim){
  return(read_csv(paste0(filedir, "", "sim_", sim, "_report.csv"))) 
}

best_gen <- function(filedir) {
  get_reports(filedir) %>% 
  group_by(sim) %>% 
  mutate(final_min_error = min(min_error)) %>% 
  filter(error == final_min_error) %>%  
  filter(row_number()==1) %>% 
  #filter(min_error < 2) %>% 
  arrange(min_error)
}

# plot_reports() plots the RMSE v generations for all the simulations in a given scenario
plot_reports <- function(filedir,  title){
  x_scale <- c(0, 100, 200, 300, 400, 500)
  
  figure <- get_reports(filedir) %>% 
    # filter(!is.na(gen)) %>% 
    filter(gen > 0) %>% 
    filter(error < 100) %>% 
    ggplot(aes(x = gen)) +
    geom_line(aes(y = error, color = "error"), color = "#CC79A7") + 
    geom_line(aes(y = min_error, color = "min error"), color = "black") +
    facet_wrap(~sim) + 
    #ggtitle(title) + 
    xlab("Generations") +
    ylab("RMSE") + 
    #ylim(c(1, 10)) + 
    #scale_x_continuous(breaks = x_scale) + 
    cowplot::theme_minimal_grid(12) + 
    theme(axis.text.x = element_text(size=11, angle= -45))
  
  return(figure)
}

logel_plot <- function(filedir, sim, gen, timestamp){

  figure <- read_tsv(paste0(filedir,"sim_", sim, "_gen_", gen, "_ID_0", ".tsv" )) %>% 
       mutate(time = round(time)) %>% 
       filter(time == timestamp) %>% 
       filter(!str_detect(species, '__|bound|ecoli|promoter|degraded')) %>% 
       #mutate(normalized = transcript/transcript[1]) %>% 
       mutate(species = factor(species, c("gene_A", "gene_A*", "gene_B",
                                         "gene_K", "gene_C", "gene_D",
                                         "gene_E", "gene_J", "gene_F",
                                         "gene_G", "gene_H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
       ggplot(aes(x=species, y=transcript, fill = species)) +
       geom_bar(stat="identity", color = "black", alpha = 0.75) + 
       scale_fill_manual(values = my_palette) + 
       #scale_y_continuous() + 
       #scale_y_continuous(limits = c(0, 18),
        #                  breaks = c(0,3,6,9,12,15,18)) +
       scale_y_continuous(limits = c(0, 300), expand = c(0,0)) +
       ylab("")+
       cowplot::theme_cowplot(12) +
       theme(legend.position = "none") 
  
  return(figure)
}

logel_plot_2 <- function(df){
  
  figure <- df %>% 
       filter(!str_detect(species, '__|bound|ecoli|promoter|degraded')) %>% 
       #mutate(normalized = transcript/transcript[1]) %>% 
       mutate(species = factor(species, c("gene_A", "gene_A*", "gene_B",
                                         "gene_K", "gene_C", "gene_D",
                                         "gene_E", "gene_J", "gene_F",
                                         "gene_G", "gene_H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
       ggplot(aes(x=species, y=transcript, fill = species)) +
       geom_bar(stat="identity", color = "black") + 
       scale_fill_manual(values = my_palette) + 
       #scale_y_continuous() + 
       #scale_y_continuous(limits = c(0, 18),
        #                  breaks = c(0,3,6,9,12,15,18)) +
       scale_y_continuous(limits = c(0, 300), expand = c(0,0)) +
       ylab("") +
       xlab("genes") + 
       cowplot::theme_cowplot(12) +
       theme(legend.position = "none") 
  
  return(figure)
}

get_fitness <- function(file, timepoint){
  
  pt_run <- as.data.frame(read_tsv(file)) %>% 
    mutate(time = round(time, 0)) %>% 
    filter(time == timepoint) %>% 
    filter(!str_detect(species, '__|bound|ecoli|promoter')) %>% 
    mutate(species = factor(species, c("gene_A", "gene_A*", "gene_B",
                                           "gene_K", "gene_C", "gene_D",
                                           "gene_E", "gene_J", "gene_F",
                                           "gene_G", "gene_H"),
                                     c("A", "A*", "B", "K",
                                           "C", "D", "E", "J",
                                           "F", "G", "H"))) %>% 
    filter(species %in% c("B", "D", "J", "F", "G", "H")) %>% 
    select(-ribo_density, -transcript, -time) %>% 
    mutate(copies = c(60, 240, 60, 60, 12, 60))  %>% # From Leuven 2020
    mutate(stoich = protein/copies) %>%
    summarise(virions = min(stoich))
  
  return(pt_run$virions[1])
}

logel_timeseries_with_pcr <- function(filedir, sim, gen1, gen2, gen3, timestamp) {
  
  sim_qpcr <- data.frame(species = c("A", "A*", "B", "K","C", "D", "E", "J","F", "G", "H"),
                        normalized = c(17, 17, 102, 102, 102, 289, 289, 289, 187, 85, 17)) %>% 
            mutate(species = factor(species, c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
            ggplot(aes(x=species, y=normalized, fill = species)) +
            geom_bar(stat="identity", color = "black") + 
            scale_fill_manual(values = my_palette) + 
            scale_y_continuous(limits = c(0, 300)) + 
            #breaks = c(0,3,6,9,12,15,18)) + 
            ggtitle("Target (qPCR)") + 
            ylab("Relative transcripts")+ 
            xlab("ΦX174 genes")+ 
            cowplot::theme_cowplot(12) +
            theme(legend.position = "none",
                  plot.title = element_text(hjust = 0.5)) 
  
  sim_start <- logel_plot(filedir, sim, gen = gen1, timestamp = timestamp) + 
               ggtitle(paste0("Generation ", gen1)) + 
               theme(plot.title = element_text(hjust = 0.5))
  sim_middle <- logel_plot(filedir, sim, gen = gen2, timestamp = timestamp) + 
                ggtitle(paste0("Generation ", gen2)) +
                theme(plot.title = element_text(hjust = 0.5))
  sim_end <- logel_plot(filedir, sim, gen = gen3, timestamp = timestamp) + 
               ggtitle(paste0("Final", "")) + 
               theme(plot.title = element_text(hjust = 0.5))
  
  #title <- ggdraw() + draw_label(paste0("", "Simulated Transcription Patterns"))
  
  figure <- cowplot::plot_grid(sim_qpcr, sim_start, sim_middle, sim_end,
                      #label_x = "genes", label_y = "transcript abundances", 
                      #labels = c("A", "B", "", ""), 
                      ncol = 4, nrow = 1)
  
  #figure <- plot_grid(panels, ncol=1, rel_heights=c(0.1, 1)) 
               
  return(figure)
}

logel_timeseries_with_rnaseq <- function(filedir, sim, gen1, gen2, gen3, timestamp) {
  
  sim_qpcr <- data.frame(species = c("A", "A*", "B", "K","C", "D", "E", "J","F", "G", "H"),
                        normalized = c(27, 27, 120, 81, 123, 228, 201, 264, 231, 118, 76)) %>% 
            mutate(species = factor(species, c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
            ggplot(aes(x=species, y=normalized, fill = species)) +
            geom_bar(stat="identity", color = "black") + 
            scale_fill_manual(values = my_palette) + 
            scale_y_continuous(limits = c(0, 300), expand = c(0,0)) + 
            #breaks = c(0,3,6,9,12,15,18)) + 
            ggtitle("Target (RNAseq)") + 
            ylab("Transcripts")+ 
            xlab("ΦX174 genes")+ 
            cowplot::theme_cowplot(12) +
            theme(legend.position = "none",
                  plot.title = element_text(hjust = 0.5)) 
  
  sim_start <- logel_plot(filedir, sim, gen = gen1, timestamp = timestamp) + 
               ggtitle(paste0("Generation ", gen1)) + 
               theme(plot.title = element_text(hjust = 0.5))
  sim_middle <- logel_plot(filedir, sim, gen = gen2, timestamp = timestamp) + 
                ggtitle(paste0("Generation ", gen2)) +
                theme(plot.title = element_text(hjust = 0.5))
  sim_end <- logel_plot(filedir, sim, gen = gen3, timestamp = timestamp) + 
               ggtitle(paste0("Final", "")) + 
               theme(plot.title = element_text(hjust = 0.5))
  
  #title <- ggdraw() + draw_label(paste0("", "Simulated Transcription Patterns"))
  
  figure <- cowplot::plot_grid(sim_qpcr, sim_start, sim_middle, sim_end,
                      #label_x = "genes", label_y = "transcript abundances", 
                      #labels = c("A", "B", "", ""), 
                      ncol = 4, nrow = 1)
  
  #figure <- plot_grid(panels, ncol=1, rel_heights=c(0.1, 1)) 
               
  return(figure)
}

exp_rnaseq <- function() {
  figure <- data.frame(species = c("A", "A*", "B", "K","C", "D", "E", "J","F", "G", "H"),
                        normalized = c(27, 27, 120, 81, 123, 228, 201, 264, 231, 118, 76)) %>% 
            mutate(species = factor(species, c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
            ggplot(aes(x=species, y=normalized, fill = species)) +
            geom_bar(stat="identity", color = "black") + 
            scale_fill_manual(values = my_palette) + 
            scale_y_continuous(limits = c(0, 300)) + 
            #breaks = c(0,3,6,9,12,15,18)) + 
            ggtitle("Target (RNA-seq)") + 
            ylab("Transcripts")+ 
            xlab("genes")+ 
            cowplot::theme_cowplot(12) +
            theme(legend.position = "none",
                  plot.title = element_text(hjust = 0.5)) 
  return(figure)
}

exp_qpcr <- function() {
  figure <- data.frame(species = c("A", "A*", "B", "K","C", "D", "E", "J","F", "G", "H"),
                        normalized = c(17, 17, 102, 102, 102, 289, 289, 289, 187, 85, 17)) %>% 
            mutate(species = factor(species, c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
            ggplot(aes(x=species, y=normalized, fill = species)) +
            geom_bar(stat="identity", color = "black") + 
            scale_fill_manual(values = my_palette) + 
            scale_y_continuous(limits = c(0, 300)) + 
            #breaks = c(0,3,6,9,12,15,18)) + 
            ggtitle("Target (qPCR)") + 
            ylab("Transcripts")+ 
            xlab("genes")+ 
            cowplot::theme_cowplot(12) +
            theme(legend.position = "none",
                  plot.title = element_text(hjust = 0.5)) 
  return(figure)
}

transcripts_vs_time_plot <- function(filedir, sim, gen){

  figure <- read_tsv(paste0(filedir,"sim_", sim, "_gen_", gen, "_ID_0", ".tsv" )) %>% 
       filter(!str_detect(species, '__|bound|ecoli|promoter|degraded')) %>% 
       mutate(species = factor(species, c("gene_A", "gene_A*", "gene_B",
                                         "gene_K", "gene_C", "gene_D",
                                         "gene_E", "gene_J", "gene_F",
                                         "gene_G", "gene_H"),
                                       c("A", "A*", "B", "K",
                                         "C", "D", "E", "J",
                                         "F", "G", "H"))) %>% 
       ggplot(aes(x=time, y=transcript, color = species)) +
       geom_line() + 
       scale_color_manual(values = my_palette) + 
       ylab("Transcript counts")+
       cowplot::theme_cowplot(12)
  
  return(figure)
}

```

```{r}
plot_reports(filedir, "RNAseq")
```

```{r}
best_gen_report <- best_gen(filedir)
best_gen_report
```

```{r}
logel_timeseries_with_rnaseq(filedir, "10", "0", "500", "5542", 500)
```

```{r}
# pA/tH correlation with worst 6 fits removed
pa_ph_corr <- best_gen_report %>% mutate(tH_mut = 1 - tH) %>%
        filter(final_min_error <= 24) %>%
        ggplot(aes(x=pA, y=tH)) +
         geom_point() + 
         scale_x_continuous(trans = "log10") +
         scale_y_continuous(trans = "log10") +
         geom_smooth(method = lm) +
         ylab("tH") +
         cowplot::theme_cowplot(12) 
```

```{r}
# Fitted parameter distributions - boxplots

#prom_palette = c("#e7e6f7", "#aea3b0", "#d0d38f")
prom_palette = c('#93D8F8', '#C27F7A', '#65AFCF', '#73B47E')
#term_palette = c("#fadf7f", "#55d6be","#acfcd9","#7FDEFF")
term_palette = c('#65AFCF', '#C994CE', '#A56EA9', '#EDB7F2', '#97D8A2')

promoter_dist <- best_gen_report %>% 
  filter(final_min_error <= 24) %>%
  select(-1:-2, -12:-15) %>%
  pivot_longer(!sim, names_to = "element", values_to = "strength") %>%
  filter(element %in% c("pA", "pB", "pD", "btss49")) %>%
  ggplot(aes(x=fct_relevel(element, "pD", "btss49", "pB", "pA"), y=strength, fill=element)) +
    geom_boxplot() +
    scale_y_continuous(limits = c(0, 40)) +
    scale_fill_manual(values = prom_palette) +
    ylab(expression("strength" ~ 
                         (10^{6} ~ M^{-1} ~ s^{-1})
                       )) +
    xlab("element") +
    cowplot::theme_cowplot(11) +
    background_grid() +
    panel_border() +
    theme(legend.position = "none") +
    coord_flip()

terminator_dist <- best_gen_report %>% 
  filter(final_min_error <= 24) %>%
  select(-1:-2, -12:-15) %>%
  pivot_longer(!sim, names_to = "element", values_to = "strength") %>%
  filter(element %in% c("RUT3", "tF", "tG", "tJ", "tH")) %>%
  ggplot(aes(x=fct_relevel(element, "tH", "tG", "tF", "tJ", "RUT3"), y=strength, fill=element)) +
    geom_boxplot() +
    scale_y_continuous(limits = c(0, 1)) +
    scale_fill_manual(values = term_palette) +
    ylab("termination probability") +
    xlab("element") +
    cowplot::theme_cowplot(11) +
    background_grid() +
    panel_border() +
    theme(legend.position = "none") +
    coord_flip()

boxplots <- cowplot::plot_grid(promoter_dist, terminator_dist,
                      #label_x = "genes", label_y = "transcript abundances", 
                      #labels = c("A", "B", "", ""), 
                      ncol = 1, nrow = 2)
cowplot::plot_grid(boxplots, pa_ph_corr,
                      #label_x = "genes", label_y = "transcript abundances", 
                      #labels = c("A", "B", "", ""), 
                      ncol = 2, nrow = 1)
```

```{r}
best_gen_report_original_model <- read_csv("../01222023/best_gen_report_rnaseq_original.csv")
```

```{r}
prom_new <- best_gen_report %>% 
  ungroup() %>%
  filter(final_min_error <= 24) %>%
  select(3:6, 14) %>%
  pivot_longer(!sim, names_to = "element", values_to = "strength") %>%
  mutate(model = "Logel")
  
prom_orig <- best_gen_report_original_model %>%
  ungroup() %>%
  select(3:5, 12) %>%
  pivot_longer(!sim, names_to = "element", values_to = "strength") %>%
  mutate(model = "original")


prom_all <- bind_rows(prom_orig, prom_new)
#prom_all$model <- factor(prom_all$model, levels=c("original", "Logel"))
prom_all %>%
  ggplot(aes(x=element, y=strength, fill=model)) +
    geom_boxplot(position = position_dodge(preserve = "single", width = 1.1)) +
    scale_y_continuous(limits = c(0, 20)) +
    ylab(expression("strength" ~ 
                         (10^{6} ~ M^{-1} ~ s^{-1})
                       )) +
    xlab("") +
    cowplot::theme_cowplot(11) +
    background_grid() +
    panel_border()
    #theme(legend.position = "none")
```

```{r}
term_new <- best_gen_report %>% 
  ungroup() %>%
  filter(final_min_error <= 24) %>%
  select(7:11, 14) %>%
  pivot_longer(!sim, names_to = "element", values_to = "strength") %>%
  mutate(model = "Logel")
  
term_orig <- best_gen_report_original_model %>%
  ungroup() %>%
  select(6:9, 12) %>%
  pivot_longer(!sim, names_to = "element", values_to = "strength") %>%
  mutate(model = "original")


term_all <- bind_rows(term_new, term_orig)
term_all %>%
  ggplot(aes(x=element, y=strength, fill=model)) +
    geom_boxplot(position = position_dodge(preserve = "single", width = 1.1)) +
    scale_y_continuous(limits = c(0, 1)) +
    ylab("termination efficiency") +
    xlab("") +
    cowplot::theme_cowplot(11) +
    background_grid() +
    panel_border()
    #theme(legend.position = "none")
```
```{r}
prom_all %>%
  ggplot(aes(x=element, y=strength, fill=model)) +
    geom_boxplot(position = position_dodge(preserve = "single", width = 1.1)) +
    scale_y_continuous(limits = c(0, 20)) +
    scale_fill_manual(values = c("#876B6E", "#beaec0")) +
    ylab(expression("strength" ~ 
                         (10^{6} ~ M^{-1} ~ s^{-1})
                       )) +
    xlab("") +
    cowplot::theme_cowplot(11) +
    background_grid() +
    panel_border()
    #theme(legend.position = "none")
```
```{r}
prom <- prom_all %>%
  ggplot(aes(x=fct_relevel(element, "pA", "pB", "btss49", "pD"), y=strength, fill=model)) +
    geom_boxplot(position = position_dodge(preserve = "single", width = 1.1)) +
    scale_y_continuous(limits = c(0, 20), expand = expansion(mult = c(0, 0))) +
    scale_fill_manual(values = c("#876B6E", "#94d7be")) +
    ylab(expression("binding strength" ~ 
                         (10^{6} ~ M^{-1} ~ s^{-1})
                       )) +
    xlab("") +
    theme_minimal() +
    background_grid() +
    panel_border(color = "gray40")

term <- term_all %>%
  ggplot(aes(x=fct_relevel(element, "RUT3", "tJ", "tF", "tG", "tH"), y=strength, fill=model)) +
    geom_boxplot(position = position_dodge(preserve = "single", width = 1.1)) +
    scale_y_continuous(limits = c(0, 1), expand = expansion(mult = c(0, 0))) +
    scale_fill_manual(labels = c("+ btss49, RUT3  ", "- btss49, RUT3"), values = c("#876B6E", "#94d7be")) +
    ylab("termination efficiency (%)") +
    xlab("") +
    theme_minimal() +
    background_grid() +
    panel_border(color = "gray40")

row <- cowplot::plot_grid(prom + theme(legend.position = "none"),
                          term + theme(legend.position = "none"),
                          align = "vh",
                          nrow = 2,
                          labels = c("A", "B"))

legend <- get_legend(
  # create some space to the left of the legend
  #term + theme(legend.box.margin = margin(0, 0, 0, 12))
  term + 
    guides(fill = guide_legend(nrow = 1, direction = "horizontal")) +
    theme(legend.position = c(.98, .98), 
          legend.justification = c(1, 1),
          plot.margin = margin(7, 7, 0, 7, "pt")) +
    labs(fill = "Model ")
)

cowplot::plot_grid(legend, row, ncol = 1, rel_heights = c(0.05, 1))
ggsave("paper_figures/rnaseq_estimates.png", width = 8, height = 6.5)
```

```{r}
logel_model <- best_gen_report %>% 
  select(final_min_error) %>%
  mutate(Model = "+ btss49, RUT3")

original_model <- best_gen_report_original_model %>%
  select(final_min_error) %>%
  mutate(Model = "- btss49, RUT3")

rmse <- bind_rows(logel_model, original_model)
rmse

t.test(final_min_error ~ Model, data = rmse)

rmse %>% ggplot(aes(x = Model, y = final_min_error)) +
  geom_boxplot(fill = "gray70") +
  scale_y_continuous(limits = c(0, 45),
                     expand = expansion(mult = c(0, 0)),
                     name = "Final RMSE") +
  theme_minimal() +
  background_grid() +
  panel_border(color = "gray40") +
  coord_flip()
ggsave("paper_figures/final_rmse_plot.png", width = 8, height = 4)
```
```{r}
best_gen_report %>% 
  ungroup() %>% 
  filter(final_min_error <= 24) %>% 
  summarise(across(everything(), list(mean)))
```

```{r}
rnaseq <- data.frame(species = c("A", "A*", "B", "K","C", "D", "E", "J","F", "G", "H"),
                      normalized = c(27, 27, 120, 81, 123, 228, 201, 264, 231, 118, 76)) %>% 
          mutate(species = factor(species, c("A", "A*", "B", "K",
                                       "C", "D", "E", "J",
                                       "F", "G", "H"),
                                     c("A", "A*", "B", "K",
                                       "C", "D", "E", "J",
                                       "F", "G", "H"))) %>% 
          ggplot(aes(x=species, y=normalized, fill = species)) +
          geom_bar(stat="identity", color = "black") + 
          scale_fill_manual(values = my_palette) + 
          scale_y_continuous(limits = c(0, 300), breaks = c(100, 200, 300), labels = c("4", "8", "12"), expand = c(0,0)) + 
          #breaks = c(0,3,6,9,12,15,18)) + 
          ggtitle("Target (RNA-seq)") + 
          ylab("Normalized transcripts")+ 
          xlab("Genes")+ 
          cowplot::theme_cowplot(12) +
          theme(legend.position = "none",
                panel.background = element_rect(fill = "gray85")) 

df_cryptic <- data.frame()
for(i in 0:4){
     tmp <- read_tsv(paste0(filedir, "/sim_17_gen_5574_ID_", i, ".tsv")) %>%
       mutate(time = round(time)) %>% 
       filter(time == 500)
     df_cryptic <- rbind(df_cryptic, tmp)}

df_cryptic <- df_cryptic %>% 
  group_by(species) %>%
  summarise(protein=mean(protein), transcript=mean(transcript), ribo_density=mean(ribo_density))

plot_cryptic <- logel_plot_2(df_cryptic) + 
               ggtitle("+ BTSS49, RUT3") +
               ylab("Simulated transcripts")

fildir_canonical <- paste("../../../../output/", "01222023", "/", sep="")
df_canonical <- data.frame()
for(i in 0:4){
     tmp <- read_tsv(paste0(fildir_canonical, "/sim_15_gen_2467_ID_", i, ".tsv")) %>%
       mutate(time = round(time)) %>% 
       filter(time == 500)
     df_canonical <- rbind(df_canonical, tmp)}

df_canonical <- df_canonical %>% 
  group_by(species) %>%
  summarise(protein=mean(protein), transcript=mean(transcript), ribo_density=mean(ribo_density))

plot_canonical <- logel_plot_2(df_canonical) + 
               ggtitle("- BTSS49, RUT3") +
               ylab("Simulated transcripts")

cowplot::plot_grid(rnaseq, plot_cryptic, plot_canonical, nrow = 1)
ggsave("paper_figures/fitted_sims_both_models.png", width = 9, height = 3)
```

```{r}
row <- cowplot::plot_grid(prom + theme(legend.position = "none"), term, nrow = 1, rel_widths = c(0.45, 0.65), labels = c("A", "B"))

row
#cowplot::plot_grid(row, legend, ncol = 2, rel_widths = c(1, 0.1))
ggsave("paper_figures/rnaseq_estimates_horizontal.png", width = 9, height = 3)
```



